const defaultLevels = {
  A1: {
    title: 'CEFR A1: Essential Everyday English',
    description: 'Basic vocabulary for everyday greetings, numbers, family, and simple routines.',
    cards: [
      { term: 'Always', definition: 'Luôn luôn', example_sentence: 'I always drink coffee in the morning.', part_of_speech: 'adverb' },
      { term: 'Family', definition: 'Gia đình', example_sentence: 'My family lives in Hanoi.', part_of_speech: 'noun' },
      { term: 'Friend', definition: 'Bạn bè', example_sentence: 'She is my best friend.', part_of_speech: 'noun' },
      { term: 'House', definition: 'Ngôi nhà', example_sentence: 'They bought a new house.', part_of_speech: 'noun' },
      { term: 'Morning', definition: 'Buổi sáng', example_sentence: 'Good morning, how are you?', part_of_speech: 'noun' },
      { term: 'Student', definition: 'Học sinh, sinh viên', example_sentence: 'He is a university student.', part_of_speech: 'noun' },
      { term: 'Teacher', definition: 'Giáo viên', example_sentence: 'Our English teacher is very kind.', part_of_speech: 'noun' },
      { term: 'Water', definition: 'Nước', example_sentence: 'Please drink more water.', part_of_speech: 'noun' },
      { term: 'Work', definition: 'Làm việc', example_sentence: 'I work from 9 AM to 5 PM.', part_of_speech: 'verb' },
      { term: 'Today', definition: 'Hôm nay', example_sentence: 'Today is a sunny day.', part_of_speech: 'noun' },
    ],
  },
  A2: {
    title: 'CEFR A2: Elementary Practical English',
    description: 'Vocabulary for shopping, travel, work, and personal hobbies.',
    cards: [
      { term: 'Advice', definition: 'Lời khuyên', example_sentence: 'Can you give me some good advice?', part_of_speech: 'noun' },
      { term: 'Borrow', definition: 'Vay, mượn', example_sentence: 'Can I borrow your pen?', part_of_speech: 'verb' },
      { term: 'Decide', definition: 'Quyết định', example_sentence: 'We need to decide where to go.', part_of_speech: 'verb' },
      { term: 'Experience', definition: 'Kinh nghiệm, trải nghiệm', example_sentence: 'Traveling gives you great experience.', part_of_speech: 'noun' },
      { term: 'Improve', definition: 'Cải thiện, nâng cao', example_sentence: 'I practice daily to improve my speaking.', part_of_speech: 'verb' },
      { term: 'Journey', definition: 'Chuyến đi, hành trình', example_sentence: 'It was a long journey across the country.', part_of_speech: 'noun' },
      { term: 'Opinion', definition: 'Ý kiến, quan điểm', example_sentence: 'What is your opinion on this matter?', part_of_speech: 'noun' },
      { term: 'Schedule', definition: 'Lịch trình, thời khóa biểu', example_sentence: 'Let me check my schedule for tomorrow.', part_of_speech: 'noun' },
      { term: 'Suggest', definition: 'Đề xuất, gợi ý', example_sentence: 'I suggest taking a break now.', part_of_speech: 'verb' },
      { term: 'Traffic', definition: 'Giao thông', example_sentence: 'There was heavy traffic on the highway.', part_of_speech: 'noun' },
    ],
  },
  B1: {
    title: 'CEFR B1: Intermediate Conversational English',
    description: 'Words to express feelings, abstract concepts, career goals, and opinions.',
    cards: [
      { term: 'Achievement', definition: 'Thành tựu, đạt được', example_sentence: 'Passing the exam was a great achievement.', part_of_speech: 'noun' },
      { term: 'Challenge', definition: 'Thử thách', example_sentence: 'Learning a new language is a fun challenge.', part_of_speech: 'noun' },
      { term: 'Confidence', definition: 'Sự tự tin', example_sentence: 'Public speaking builds self-confidence.', part_of_speech: 'noun' },
      { term: 'Environment', definition: 'Môi trường', example_sentence: 'We must protect the environment.', part_of_speech: 'noun' },
      { term: 'Opportunity', definition: 'Cơ hội', example_sentence: 'Working abroad is a fantastic opportunity.', part_of_speech: 'noun' },
      { term: 'Participate', definition: 'Tham gia', example_sentence: 'Many students participate in sports.', part_of_speech: 'verb' },
      { term: 'Recommend', definition: 'Giới thiệu, tiến cử', example_sentence: 'I highly recommend this book.', part_of_speech: 'verb' },
      { term: 'Solution', definition: 'Giải pháp', example_sentence: 'We found a smart solution to the problem.', part_of_speech: 'noun' },
      { term: 'Strategy', definition: 'Chiến lược', example_sentence: 'A clear strategy ensures project success.', part_of_speech: 'noun' },
      { term: 'Succeed', definition: 'Thành công', example_sentence: 'If you work hard, you will succeed.', part_of_speech: 'verb' },
    ],
  },
  B2: {
    title: 'CEFR B2: Upper-Intermediate Professional English',
    description: 'Advanced vocabulary for technical debates, business, and complex texts.',
    cards: [
      { term: 'Accurate', definition: 'Chính xác', example_sentence: 'The report contains accurate financial data.', part_of_speech: 'adjective' },
      { term: 'Analyze', definition: 'Phân tích', example_sentence: 'Data scientists analyze complex datasets.', part_of_speech: 'verb' },
      { term: 'Collaborate', definition: 'Hợp tác, cộng tác', example_sentence: 'Our team collaborates with international partners.', part_of_speech: 'verb' },
      { term: 'Efficient', definition: 'Hiệu quả, năng suất', example_sentence: 'Automation makes the workflow more efficient.', part_of_speech: 'adjective' },
      { term: 'Flexible', definition: 'Linh hoạt', example_sentence: 'We offer flexible working hours.', part_of_speech: 'adjective' },
      { term: 'Implement', definition: 'Thực thi, triển khai', example_sentence: 'We will implement the new security policy.', part_of_speech: 'verb' },
      { term: 'Negotiate', definition: 'Đàm phán, thương lượng', example_sentence: 'They negotiated a new contract.', part_of_speech: 'verb' },
      { term: 'Perspective', definition: 'Góc nhìn, viễn cảnh', example_sentence: 'Try to see the issue from another perspective.', part_of_speech: 'noun' },
      { term: 'Relevant', definition: 'Liên quan, thích hợp', example_sentence: 'Please provide all relevant information.', part_of_speech: 'adjective' },
      { term: 'Sustain', definition: 'Duy trì, chống chịu', example_sentence: 'Solar energy helps sustain natural resources.', part_of_speech: 'verb' },
    ],
  },
  C1: {
    title: 'CEFR C1: Advanced Academic & Professional English',
    description: 'Nuanced vocabulary for high-level academic writing and executive discourse.',
    cards: [
      { term: 'Ambiguity', definition: 'Sự mơ hồ, không rõ ràng', example_sentence: 'Avoid ambiguity in legal documents.', part_of_speech: 'noun' },
      { term: 'Comprehensive', definition: 'Toàn diện, bao quát', example_sentence: 'They published a comprehensive study.', part_of_speech: 'adjective' },
      { term: 'Discrepancy', definition: 'Sự khác biệt, sự bất đồng', example_sentence: 'There is a discrepancy in the audit numbers.', part_of_speech: 'noun' },
      { term: 'Elaborate', definition: 'Chi tiết, phác thảo kỹ', example_sentence: 'Could you elaborate on your proposal?', part_of_speech: 'verb' },
      { term: 'Feasible', definition: 'Khả thi, thực tế', example_sentence: 'Building a subway line here is economically feasible.', part_of_speech: 'adjective' },
      { term: 'Implicit', definition: 'Ngầm hiểu, ẩn ý', example_sentence: 'Her nod gave implicit agreement.', part_of_speech: 'adjective' },
      { term: 'Meticulous', definition: 'Tỉ mỉ, cẩn thận từng chi tiết', example_sentence: 'He gave a meticulous presentation.', part_of_speech: 'adjective' },
      { term: 'Predominant', definition: 'Chiếm ưu thế, chủ đạo', example_sentence: 'English is the predominant language in global trade.', part_of_speech: 'adjective' },
      { term: 'Substantial', definition: 'Đáng kể, quan trọng', example_sentence: 'We achieved substantial progress this quarter.', part_of_speech: 'adjective' },
      { term: 'Versatile', definition: 'Đa năng, linh hoạt', example_sentence: 'Python is a highly versatile programming language.', part_of_speech: 'adjective' },
    ],
  },
  C2: {
    title: 'CEFR C2: Master & Native-Level Proficiency',
    description: 'Literary, sophisticated terms for complete mastery of expression and nuance.',
    cards: [
      { term: 'Acquiesce', definition: 'Bằng lòng, chấp thuận ngầm', example_sentence: 'He decided to acquiesce to their demands.', part_of_speech: 'verb' },
      { term: 'Cognizant', definition: 'Nhận thức rõ, ngộ ra', example_sentence: 'Leaders must be cognizant of emerging risks.', part_of_speech: 'adjective' },
      { term: 'Ephemeral', definition: 'Phù du, chóng khánh', example_sentence: 'Fame in modern media can be ephemeral.', part_of_speech: 'adjective' },
      { term: 'Equanimity', definition: 'Sự bình thản, điềm tĩnh', example_sentence: 'She handled the crisis with remarkable equanimity.', part_of_speech: 'noun' },
      { term: 'Fastidious', definition: 'Cầu kỳ, kén chọn', example_sentence: 'The chef is fastidious about ingredients.', part_of_speech: 'adjective' },
      { term: 'Inscrutable', definition: 'Bí hiểm, khó hiểu', example_sentence: 'His expression remained inscrutable throughout the trial.', part_of_speech: 'adjective' },
      { term: 'Lucid', definition: 'Minh mẫn, rõ ràng', example_sentence: 'She offered a extraordinarily lucid explanation.', part_of_speech: 'adjective' },
      { term: 'Paradigm', definition: 'Mô hình, kiểu mẫu', example_sentence: 'Quantum computing is a new computing paradigm.', part_of_speech: 'noun' },
      { term: 'Quintessential', definition: 'Tinh túy, điển hình nhất', example_sentence: 'It is the quintessential British afternoon tea.', part_of_speech: 'adjective' },
      { term: 'Ubiquitous', definition: 'Có mặt ở khắp mọi nơi', example_sentence: 'Smartphones are now ubiquitous in modern life.', part_of_speech: 'adjective' },
    ],
  },
};

module.exports = defaultLevels;
